# Full Scan Summary Template

Template for `.project-ingest/scans/full-scan-summary.md`

---

## Output
Full Scan Summary

Metadata

Scan Date: [timestamp]
Mode: [fresh / incremental]
Boundaries Scanned: [list]
Categories Scanned: 12 / 12
Total Duration: [time]
Findings Overview

Category	Findings	Definite	Potential	[If incremental] New	[If incremental] Resolved
Architecture	[n]	[n]	[n]	[n]	[n]
Code Quality	[n]	[n]	[n]	[n]	[n]
Security	[n]	[n]	[n]	[n]	[n]
Performance	[n]	[n]	[n]	[n]	[n]
Testing	[n]	[n]	[n]	[n]	[n]
DevOps/CI/CD	[n]	[n]	[n]	[n]	[n]
Documentation	[n]	[n]	[n]	[n]	[n]
Dependencies	[n]	[n]	[n]	[n]	[n]
Accessibility	[n]	[n]	[n]	[n]	[n]
Standards	[n]	[n]	[n]	[n]	[n]
Observability	[n]	[n]	[n]	[n]	[n]
Data	[n]	[n]	[n]	[n]	[n]
TOTAL	[n]	[n]	[n]	[n]	[n]
Narrative Summary

[2-4 paragraphs noting:

Which categories had the most signal and what that suggests
Any cross-category patterns visible at the scan level
Which boundaries had the most findings
Areas that were clean / well-maintained
Any areas that couldn't be fully assessed and why]
Findings by Boundary

Boundary	Total Findings	Top Categories
[name]	[n]	[top 3 categories]
[name]	[n]	[top 3 categories]
Cross-Boundary Findings

ID	Description	Boundaries Involved
[id]	[brief description]	[boundary1, boundary2]
Skipped Areas (All Categories)

Path	Reason
[path]	[reason]
Generated by ingest:scan on [timestamp]